# Site settings
title: Soreine
email: hello@soreine.dev
description: "Soreine's personal website" # > this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://soreine.github.io" # the base hostname & protocol for your site
github_username: Soreine
permalink: pretty
exclude:
  - css/style.styl
  - Gemfile
  - Gemfile.lock
  - README.md
  - working/
# Used to create a for loop for breadcrumb
breadcrumb_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
# Build settings
markdown: kramdown
highlighter: rouge
breadcrumbs:
  root:
    hide: false # show breadcrumbs on root/home page
    image: false # Show image or title text
